# Generated by Django 5.1.1 on 2024-10-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_rename_describtion_cat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст (в месяцах)'),
        ),
    ]
